### ISSUE TITLE
SQL update never finishes

### ISSUE THREAD

**Issue by tylerlong** [sosedoff/pgweb#99] opened 2015-10-12 04:16 UTC
I notices this several times.  I have a SQL update statement (or create index statement) which will take around 3 minutes (measured in psql). When I execute this statement in pgweb, it never finishes and I have to wait for ever.

I think it is because the frontend of pgweb timeouts and it won't wait for PostgreSQL to finish. So the frontend never updates even when the statement execution is finished.

How to reproduce the prolem: just create a table and populate it with millions of data. Then try to create index on a string column. We know that it might take minutes to hours to finish. But inside pgweb, the frontend never tell you that  it's finished no matter how long you wait(even days).

**Comment by cbandy** [comment] 2015-10-12 04:41
This may be easier to reproduce with `pg_sleep()`.

**Comment by sosedoff** [comment] 2015-10-12 05:09
@tylerlong did the issue only appear on longer (hours) requests? The behavior is indeed a bug, but i personally havent tested pgweb with longer running queries since it was not intended for that in the first place. Im currently running a long test using `pg_sleep`, maybe i can reproduce the bug.

**Comment by tylerlong** [comment] 2015-10-12 05:22
@cbandy brilliant idea!

@sosedoff  Yes only appear on longer requests. But not hours, minutes is able to reproduce.

I just tested this: `SELECT pg_sleep(300);`. This should be finished in 300 seconds, aka 5 minutes. But I have been waiting for 30 minutes and I am still waiting. I don't think pgweb will ever tell me that it's finished.

**Comment by sosedoff** [comment] 2015-10-12 05:32
@tylerlong i was able to run sleep query for 300 seconds, and web ui responded correctly. could you specify your stack? (postgresql version, web browser and its version). also, are you running latest pgweb version too?

**Comment by tylerlong** [comment] 2015-10-12 10:45
@sosedoff I just tested latest version with Chrome browser, it did work without problem.

What I had problem is Cocoa webview: https://developer.apple.com/library/mac/documentation/Cocoa/Reference/WebKit/Classes/WebView_Class/

So this might not be pgweb's issue. Let me test more and get back to you later.

**Comment by sosedoff** [comment] 2015-10-20 02:23
@tylerlong im going to close this for now, feel free to reopen the issue once you have some steps to reproduce the issue.

**Closed by sosedoff** 2015-10-20 02:23 UTC
