### ISSUE TITLE
Pgweb Pro ?

### ISSUE THREAD

**Issue by Davincible** [sosedoff/pgweb#567] opened 2022-06-16 14:06 UTC
I just noticed the Pgweb Pro section in the readme, and was curious about it since it sounds nice. 

Just had a few questions;
* Will this also be open source (The 'Pro' makes it sound paid)?
* Any ETA?

**Comment by sosedoff** [comment] 2022-06-22 02:13
The Pro project is currently on hold due to limited bandwidth for OSS work on my end, although the Pro was intended to be released as a closed-source only. For what its worth, you can find plenty of similar tools that would suit your needs, like https://popsql.com/.

**Closed by sosedoff** 2022-06-22 02:13 UTC
