### ISSUE TITLE
Error: pq: schema "dbms_rls" does not exist

### ISSUE THREAD

**Issue by zoujd-github** [sosedoff/pgweb#222] opened 2017-02-15 09:09 UTC
[root]# /opt/go/pgweb  --url postgres://test:test@10.88.0.1:5444/ptgbdb?sslmode=disable 
Pgweb v0.9.6
Connecting to server...
Checking database objects...
Error: pq: schema "dbms_rls" does not exist

**Comment by zoujd-github** [comment] 2017-02-15 09:10
pgweb start error

**Comment by zoujd-github** [comment] 2017-02-15 09:52
but this schema "dbms_rls" is exist,wy?
![image](https://cloud.githubusercontent.com/assets/19323469/22968928/71aa1046-f3a7-11e6-849c-89d56da6365f.png)

**Comment by sosedoff** [comment] 2017-02-25 20:10
Are you using the same user for pgweb and your other db tool? I might suspect it has something to do with permissions.

**Comment by sosedoff** [comment] 2017-05-11 03:42
@zoujd-github ping, care to provide more details? otherwise i will close this issue since i don't have any way to reproduce the problem.

**Comment by sosedoff** [comment] 2017-06-06 03:46
Closing due to no response.

**Closed by sosedoff** 2017-06-06 03:46 UTC
