### ISSUE TITLE
Client generates invalid API call on data export

### ISSUE THREAD

**Issue by adkinsjd** [sosedoff/pgweb#427] opened 2019-04-09 00:57 UTC
When I try to export data, the client seems to form an invalid API call to the backend. 

For example, clicking the CSV export button calls the backend with the (improperly formatted) url:
```https://subdomain.mypgweb.io/?pg_host=my.postgres.location.ioapi/query?format=csv&query=c2VsZWN0ICogZnJvbSBkZXZpY2VzOw..&_session_id=a-session-id```

If I modify the call to remove the pg_host parameter like so:
```https://subdomain.mypgweb.io/api/query?format=csv&query=c2VsZWN0ICogZnJvbSBkZXZpY2VzOw..&_session_id=a-session-id```

or fix the url to be properly formatted without removing the pg_host parameter:
```https://subdomain.mypgweb.io/api/query?pg_host=my.postgres.location.io&format=csv&query=c2VsZWN0ICogZnJvbSBkZXZpY2VzOw..&_session_id=a-session-id```

it works as expected.

I am running 0.11.1, and I don't believe this issue was addressed in 0.11.2.

**Comment by adkinsjd** [comment] 2019-04-09 02:21
I should also note that the issue could be specific to my browser or session. I have colleagues using the same pgweb instance, connecting to the same postgres host who can successfully export data on their machines.

**Comment by sosedoff** [comment] 2019-04-09 22:11
Hi sorry i dont have much time to troubleshoot your issue, but it seems like you have a custom session, pgweb does not use the `pg_host` param. Are you setting `--prefix` option at all?

**Comment by adkinsjd** [comment] 2019-04-10 01:40
No worries, I need to export so rarely that I'm fine manually changing the URL, mostly just wanted to document the potential issue.

The only option being used is ```--sessions``` . This is technically being set through the environment variable, although I assume that's equivalent.

**Comment by sosedoff** [comment] 2019-07-05 22:00
I can't reproduce this issue at all. If you're running pgweb behind a reverse proxy or any other tool it might be worth checking out the configuration. I would appreciate if you could send some instructions to reproduce.

**Comment by adkinsjd** [comment] 2019-07-06 04:27
I am running the published 0.11.1 docker container on Google Kubernetes Engine. The configuration file for the K8s deployment, service, and ingress is here https://github.com/lab11/PlugWatch/blob/master/powerwatch/cloud/kubernetes/pgweb/pgweb-deployment.yaml

Google is running a reverse proxy for the ingress, but I don't have much control over its configuration, and I have the same ingress configuration working for many other services.

I understand this might not be the easiest to replicate. I would have time to replicate/document my process on a new cluster and providing you with access in a few days if you are interested.

**Comment by sosedoff** [comment] 2022-12-03 05:11
It has been more than a few days :) Closing!

**Closed by sosedoff** 2022-12-03 05:11 UTC
