### ISSUE TITLE
[Feature Request] Ability to enlarge query area.

### ISSUE THREAD

**Issue by charlieSplittstoser** [sosedoff/pgweb#472] opened 2020-06-03 23:28 UTC
The query area feels very small. I would sometimes like to expand it to be about half the vertical height of the screen when I am working on a query.

Conceptual image: https://prnt.sc/stbvcl

**Comment by foadgr** [comment] 2020-06-29 17:38
Agreed -- @sosedoff an adjustable/draggable query pane would be very helpful to view an entire query.

**Comment by sosedoff** [comment] 2020-06-30 00:36
This is a duplicate of #118, which is sadly i dont have time to work on :(

**Closed by sosedoff** 2020-06-30 00:36 UTC
